# Data loading

## 3dMD

In [18]:
import pyvista as pv

mesh_path = '/Users/knpob/Territory/2-Kolmo/4-Dataset/20211229-Running breast scanning/3dmd/0kmh_8marker_bra/static_standing_with_bra.000001.obj'
mesh = pv.read(mesh_path)
texture = pv.read_texture(mesh_path.replace('.obj', '.jpg'))

In [4]:
import numpy as np

points_3dmd = np.load('output/kps_3dmd.npy')
points_3dmd

array([[-143.96188043,  881.45735289,  -98.9645099 ],
       [ 148.52799833,  870.26257573,  -93.62949312],
       [  -4.37306098,  851.9689428 ,  -37.67802522],
       [ -90.61482504,  675.84718877,   29.62051627],
       [  90.39046384,  670.61744481,   40.47232367],
       [ -10.44260082,  599.83449454,   22.99841298],
       [ -82.13630439,  570.44959206,  -13.54744372],
       [  64.12592594,  562.4611924 ,   -9.3972195 ]])

## Vicon

In [66]:
import pandas as pd

vicon_path = '/Users/knpob/Territory/2-Kolmo/4-Dataset/20211229-Running breast scanning/vicon/0kmh_8marker_bra.csv'
df = pd.read_csv(vicon_path, skiprows=4).iloc[:, 2:].dropna(axis=1)
df

mm.6       mm.7         mm.8       mm.12       mm.13        mm.14  \
0     37.456169  43.442940  1391.134155  187.941772  101.022385  1409.022217   
1     37.447746  43.428123  1391.129028  187.932739  101.001129  1409.023071   
2     37.436192  43.407715  1391.122192  187.920273  100.972290  1409.024292   
3     37.421516  43.381760  1391.113770  187.904358  100.936157  1409.025757   
4     37.403969  43.350712  1391.103760  187.885315  100.893623  1409.027832   
...         ...        ...          ...         ...         ...          ...   
1339  21.732576  46.049854  1392.696899  172.232254  104.020699  1410.857788   
1340  21.720249  46.030117  1392.699097  172.221863  104.001320  1410.864868   
1341  21.713167  46.018551  1392.700562  172.215820  103.990166  1410.869141   
1342  21.710215  46.013653  1392.701172  172.213287  103.985519  1410.870850   
1343  21.709587  46.012608  1392.701294  172.212738  103.984528  1410.871216   

           mm.15       mm.16        mm.17       mm.18  ...        mm.23  \
0    -104.438118  105.529312  1419.012329  128.654831  ...  1219.265503   
1    -104.443703  105.523132  1419.006226  128.646561  ...  1219.252319   
2    -104.451866  105.513885  1418.998047  128.635010  ...  1219.234619   
3    -104.462830  105.501183  1418.988037  128.620026  ...  1219.212158   
4    -104.476746  105.484787  1418.976562  128.601730  ...  1219.185669   
...          ...         ...          ...         ...  ...          ...   
1339 -120.668114  108.256409  1418.401001  114.817039  ...  1221.327515   
1340 -120.676918  108.246849  1418.401123  114.807938  ...  1221.329468   
1341 -120.681984  108.241119  1418.401245  114.802795  ...  1221.330444   
1342 -120.684128  108.238655  1418.401245  114.800659  ...  1221.330811   
1343 -120.684578  108.238113  1418.401245  114.800217  ...  1221.330933   

          mm.24      mm.25        mm.26       mm.27     mm.28        mm.29  \
0     26.529520 -32.100250  1142.538574  104.434242 -5.804446  1102.953613   
1     26.523537 -32.092136  1142.527466  104.425392 -5.801078  1102.948730   
2     26.515257 -32.081310  1142.512573  104.413223 -5.796293  1102.942383   
3     26.504631 -32.067921  1142.493652  104.397774 -5.789944  1102.934692   
4     26.491705 -32.052292  1142.471191  104.379196 -5.781878  1102.926270   
...         ...        ...          ...         ...       ...          ...   
1339  13.241052 -34.002808  1146.459595   92.845680 -7.972306  1106.456787   
1340  13.233658 -34.026825  1146.470215   92.847748 -7.997967  1106.470947   
1341  13.229522 -34.040791  1146.476318   92.849220 -8.012938  1106.479126   
1342  13.227830 -34.046677  1146.478882   92.849915 -8.019262  1106.482788   
1343  13.227476 -34.047932  1146.479370   92.850082 -8.020615  1106.483398   

          mm.39     mm.40        mm.41  
0    -48.108265  2.692609  1110.355713  
1    -48.108398  2.705920  1110.348633  
2    -48.108650  2.723659  1110.338623  
3    -48.109077  2.745513  1110.325684  
4    -48.109814  2.770850  1110.310547  
...         ...       ...          ...  
1339 -62.898724 -0.365181  1112.024170  
1340 -62.910019 -0.384356  1112.029297  
1341 -62.916359 -0.395396  1112.032349  
1342 -62.918961 -0.400011  1112.033447  
1343 -62.919506 -0.400992  1112.033691  

[1344 rows x 24 columns]

In [75]:
frame = 0
points_vicon = df.values[frame].reshape(-1, 3)
points_vicon

array([[  37.456169,   43.44294 , 1391.134155],
       [ 187.941772,  101.022385, 1409.022217],
       [-104.438118,  105.529312, 1419.012329],
       [ 128.654831,  -44.211311, 1212.407227],
       [ -58.276783,  -39.306023, 1219.265503],
       [  26.52952 ,  -32.10025 , 1142.538574],
       [ 104.434242,   -5.804446, 1102.953613],
       [ -48.108265,    2.692609, 1110.355713]])

## Visualization

In [78]:
scene = pv.Plotter()
scene.add_points(points_3dmd, point_size=10, color='yellow', render_points_as_spheres=True)
scene.add_points(points_vicon, point_size=10, color='green', render_points_as_spheres=True)
scene.add_mesh(mesh, texture=texture)
scene.camera_position = 'xy'
scene.show()

Widget(value="<iframe src='http://localhost:58075/index.html?ui=P_0x7fc60a719580_24&reconnect=auto' style='wid…

# Registration

## Pre-alignment

In [83]:
from mesh4d import obj3d

pcd_vicon = obj3d.np2pcd(points_vicon)
r_pre = pcd_vicon.get_rotation_matrix_from_xyz((-np.pi/2, 0, 0))
pcd_vicon.rotate(r_pre, center=(0, 0, 0))
points_vicon_pre = obj3d.pcd2np(pcd_vicon)

In [84]:
scene = pv.Plotter()
scene.add_points(points_3dmd, point_size=10, color='yellow', render_points_as_spheres=True)
scene.add_points(points_vicon_pre, point_size=10, color='green', render_points_as_spheres=True)
scene.add_mesh(mesh, texture=texture)
scene.camera_position = 'xy'
scene.show()

Widget(value="<iframe src='http://localhost:58075/index.html?ui=P_0x7fc60a719e50_25&reconnect=auto' style='wid…

## Refined registration with CPD

In [86]:
from probreg import cpd
tf, _, _ = cpd.registration_cpd(points_vicon_pre, points_3dmd, 'rigid')

r_cab = tf.rot
s = tf.scale
t = tf.t

# combine pre-alignment and registration
r = np.matmul(r_cab, r_pre)

points_vicon_cab = tf.transform(points_vicon_pre)

In [88]:
scene = pv.Plotter()
scene.add_points(points_3dmd, point_size=10, color='yellow', render_points_as_spheres=True)
scene.add_points(points_vicon_cab, point_size=10, color='green', render_points_as_spheres=True)
scene.add_mesh(mesh, texture=texture)
scene.camera_position = 'xy'
scene.show()

Widget(value="<iframe src='http://localhost:58075/index.html?ui=P_0x7fc64f0fffd0_27&reconnect=auto' style='wid…

# Save calibration parameters

In [91]:
from mesh4d import field

trans_cab = field.Trans_Rigid()
trans_cab.rot = r
trans_cab.scale = s
trans_cab.t = t

In [ ]:
from mesh4d import utils

utils.save_pkl_object(trans_cab, export_folder='output', export_name='vicon>>3dmd')

## Train set validation

In [93]:
trans_cab.shift_points(points_vicon) - points_vicon_cab

array([[ 0.00000000e+00,  0.00000000e+00,  7.10542736e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  2.27373675e-13,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.84217094e-14,  0.00000000e+00,  2.84217094e-14],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.42108547e-14],
       [-1.42108547e-14,  2.27373675e-13, -7.10542736e-15]])

## Test set validation